In [1]:
 import numpy as np
np.__version__

'2.3.2'

In [2]:
arr = np.array([[1,2,3,4]])
print(arr)
print(type(arr))

[[1 2 3 4]]
<class 'numpy.ndarray'>


In [3]:
print(arr.ndim)

2


In [4]:
print(arr[0::1])

[[1 2 3 4]]


In [5]:
arr = np.array([1.1 , 3.2 , 5.2])
new_arr = arr.astype('i')
print(new_arr)

[1 3 5]


In [6]:
a = [1,2,3,4]
print(type(a))

<class 'list'>


In [7]:
arr = np.array([1,2,3,4,5,6,67,11,32,123,321,454])
newarr = arr.reshape(4,3)
newarr

array([[  1,   2,   3],
       [  4,   5,   6],
       [ 67,  11,  32],
       [123, 321, 454]])

In [8]:
arr1 = np.array([1,2,3,4,5,6,7,8])
arr2 = np.array([9,10,11])
new_arr = np.concatenate((arr1 , arr2) , axis = 0)
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [9]:
arr = np.array([1,2,3,4,5,6,7,8])
new_arr = np.array_split(arr , 2)
print(new_arr)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


In [10]:
arr = np.array([0,1,2,3,4,5,6,7,8,9,90])
where = np.where(arr % 2 == 0)
print(where)
print(arr[arr % 2 == 0])

(array([ 0,  2,  4,  6,  8, 10]),)
[ 0  2  4  6  8 90]


In [11]:
from numpy import random

In [12]:
num = random.randint(0,100)
print(num)

86


In [13]:

num = random.rand()
print(num)

0.045259049566629406


In [14]:
num = random.randint(100 , size = (10))
print(num)

[ 3 35 24 59 32 55 75  9 30 28]


In [15]:
num = random.randint(100 , size =( 3 , 5))
print(num)

[[54 55 47 19 57]
 [26 52  3 22 97]
 [11 94 75 54  1]]


In [16]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
new_arr = np.add(arr2 , arr2)
new_arr

array([ 8, 10, 12])

In [17]:
arr = 1.3214234523525252
new_arr = np.around(arr , 2)
new_arr 

np.float64(1.32)

In [18]:
arr = 1.6214234523525252
new_arr = np.floor(arr)
new_arr 

np.float64(1.0)

In [19]:
arr1 = np.array([[1,2] , [3,4]])
arr1 

array([[1, 2],
       [3, 4]])

In [20]:
arr2 = np.matrix([[1,2] , [3,4]])
arr2

matrix([[1, 2],
        [3, 4]])

In [21]:
arr1 @ arr2

matrix([[ 7, 10],
        [15, 22]])

In [22]:
a = np.dot(arr1 , arr2)
a

matrix([[ 7, 10],
        [15, 22]])

In [23]:
np.multiply(arr1 , arr2)

matrix([[ 1,  4],
        [ 9, 16]])

In [24]:
np.prod(arr1)

np.int64(24)

In [25]:
c = np.ones((3,3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
d = np.array([5,6,7])
a = c+d
a

array([[6., 7., 8.],
       [6., 7., 8.],
       [6., 7., 8.]])

In [27]:
np.sum(a)

np.float64(63.0)

In [28]:
np.size(a)

9

In [29]:
np.mean(a)

np.float64(7.0)

In [30]:
np.prod(a)

np.float64(37933056.0)

In [31]:

data = np.array([180, 160, 170, 175, 165])

print("Mean:", np.mean(data))      # میانگین
print("Variance:", np.var(data))   # واریانس

Mean: 170.0
Variance: 50.0


In [32]:
import pandas as pd
pd.__version__

'2.3.1'

In [33]:
my_arr = ([[1,2,3,4] , [5,6,7,8] , [9,10,11,12]])
my_df = pd.DataFrame(my_arr , index = ['A' , 'B' , 'C'] , columns = ['col1','col2','col3','col4'])
my_df

col1  col2  col3  col4
A     1     2     3     4
B     5     6     7     8
C     9    10    11    12

In [34]:
my_df.loc['C']['col1']

np.int64(9)

In [35]:
my_df.iloc[0]

col1    1
col2    2
col3    3
col4    4
Name: A, dtype: int64

In [36]:
my_df.iloc[2][2]

C:\Users\PARS SYS\AppData\Local\Temp\ipykernel_9288\369382682.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  my_df.iloc[2][2]


np.int64(11)

In [37]:
my_df["col5"] = [8,88,888]
my_df

col1  col2  col3  col4  col5
A     1     2     3     4     8
B     5     6     7     8    88
C     9    10    11    12   888

In [38]:
my_df.loc[["A","B"] , "col2"] = "ALI"
my_df

C:\Users\PARS SYS\AppData\Local\Temp\ipykernel_9288\4085656764.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'ALI' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  my_df.loc[["A","B"] , "col2"] = "ALI"


col1 col2  col3  col4  col5
A     1  ALI     3     4     8
B     5  ALI     7     8    88
C     9   10    11    12   888

In [39]:
my_df.dtypes

col1     int64
col2    object
col3     int64
col4     int64
col5     int64
dtype: object

In [40]:
my_df['col2'] = pd.to_numeric(my_df['col2'] , errors='coerce')
my_df

col1  col2  col3  col4  col5
A     1   NaN     3     4     8
B     5   NaN     7     8    88
C     9  10.0    11    12   888

In [41]:
my_df.dtypes

col1      int64
col2    float64
col3      int64
col4      int64
col5      int64
dtype: object

In [42]:
my_df.col1 = ['{:.2f}'.format(float(x)) for x in my_df.iloc[:,0]]
my_df

col1  col2  col3  col4  col5
A  1.00   NaN     3     4     8
B  5.00   NaN     7     8    88
C  9.00  10.0    11    12   888

In [43]:
my_df["col5"] = my_df["col5"].apply (lambda x: '{:.2f}' . format(float(x)))
my_df

col1  col2  col3  col4    col5
A  1.00   NaN     3     4    8.00
B  5.00   NaN     7     8   88.00
C  9.00  10.0    11    12  888.00

In [44]:
df = my_df.astype(float) . applymap("{:.2f}".format)
df

C:\Users\PARS SYS\AppData\Local\Temp\ipykernel_9288\1438249706.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = my_df.astype(float) . applymap("{:.2f}".format)


col1   col2   col3   col4    col5
A  1.00    nan   3.00   4.00    8.00
B  5.00    nan   7.00   8.00   88.00
C  9.00  10.00  11.00  12.00  888.00

In [45]:
my_df.drop('col4' , axis = 1 , inplace=True)
my_df

col1  col2  col3    col5
A  1.00   NaN     3    8.00
B  5.00   NaN     7   88.00
C  9.00  10.0    11  888.00

In [46]:
my_df.rename(columns={'col3' : 'COOOOOOOOL3'} , inplace= True)
my_df

col1  col2  COOOOOOOOL3    col5
A  1.00   NaN            3    8.00
B  5.00   NaN            7   88.00
C  9.00  10.0           11  888.00

In [47]:
df = pd.read_csv(r'E:\Python video\Data Analaysis (MFT)\data1.csv')
df

Car       Model  Volume  Weight  CO2
0       Toyoty        Aygo    1000     790   99
1   Mitsubishi  Space Star    1200    1160   95
2        Skoda      Citigo    1000     929   95
3         Fiat         500     900     865   90
4         Mini      Cooper    1500    1140  105
5           VW         Up!    1000     929  105
6        Skoda       Fabia    1400    1109   90
7     Mercedes     A-Class    1500    1365   92
8         Ford      Fiesta    1500    1112   98
9         Audi          A1    1600    1150   99
10     Hyundai         I20    1100     980   99
11      Suzuki       Swift    1300     990  101
12        Ford      Fiesta    1000    1112   99
13       Honda       Civic    1600    1252   94
14      Hundai         I30    1600    1326   97
15        Opel       Astra    1600    1330   97
16         BMW           1    1600    1365   99
17       Mazda           3    2200    1280  104
18       Skoda       Rapid    1600    1119  104
19        Ford       Focus    2000    1328  105
20        Ford      Mondeo    1600    1584   94
21        Opel    Insignia    2000    1428   99
22    Mercedes     C-Class    2100    1365   99
23       Skoda     Octavia    1600    1415   99
24       Volvo         S60    2000    1415   99
25    Mercedes         CLA    1500    1465  102
26        Audi          A4    2000    1490  104
27        Audi          A6    2000    1725  114
28       Volvo         V70    1600    1523  109
29         BMW           5    2000    1705  114
30    Mercedes     E-Class    2100    1605  115
31       Volvo        XC70    2000    1746  117
32        Ford       B-Max    1600    1235  104
33         BMW         216    1600    1390  108
34        Opel      Zafira    1600    1405  109
35    Mercedes         SLK    2500    1395  120

In [48]:
df.to_string()

'           Car       Model  Volume  Weight  CO2\n0       Toyoty        Aygo    1000     790   99\n1   Mitsubishi  Space Star    1200    1160   95\n2        Skoda      Citigo    1000     929   95\n3         Fiat         500     900     865   90\n4         Mini      Cooper    1500    1140  105\n5           VW         Up!    1000     929  105\n6        Skoda       Fabia    1400    1109   90\n7     Mercedes     A-Class    1500    1365   92\n8         Ford      Fiesta    1500    1112   98\n9         Audi          A1    1600    1150   99\n10     Hyundai         I20    1100     980   99\n11      Suzuki       Swift    1300     990  101\n12        Ford      Fiesta    1000    1112   99\n13       Honda       Civic    1600    1252   94\n14      Hundai         I30    1600    1326   97\n15        Opel       Astra    1600    1330   97\n16         BMW           1    1600    1365   99\n17       Mazda           3    2200    1280  104\n18       Skoda       Rapid    1600    1119  104\n19        Ford     

In [49]:
pd.options.display.max_rows = 7
df

Car       Model  Volume  Weight  CO2
0       Toyoty        Aygo    1000     790   99
1   Mitsubishi  Space Star    1200    1160   95
2        Skoda      Citigo    1000     929   95
..         ...         ...     ...     ...  ...
33         BMW         216    1600    1390  108
34        Opel      Zafira    1600    1405  109
35    Mercedes         SLK    2500    1395  120

[36 rows x 5 columns]

In [50]:
pd.set_option('display.max_rows', None)
df

Car       Model  Volume  Weight  CO2
0       Toyoty        Aygo    1000     790   99
1   Mitsubishi  Space Star    1200    1160   95
2        Skoda      Citigo    1000     929   95
3         Fiat         500     900     865   90
4         Mini      Cooper    1500    1140  105
5           VW         Up!    1000     929  105
6        Skoda       Fabia    1400    1109   90
7     Mercedes     A-Class    1500    1365   92
8         Ford      Fiesta    1500    1112   98
9         Audi          A1    1600    1150   99
10     Hyundai         I20    1100     980   99
11      Suzuki       Swift    1300     990  101
12        Ford      Fiesta    1000    1112   99
13       Honda       Civic    1600    1252   94
14      Hundai         I30    1600    1326   97
15        Opel       Astra    1600    1330   97
16         BMW           1    1600    1365   99
17       Mazda           3    2200    1280  104
18       Skoda       Rapid    1600    1119  104
19        Ford       Focus    2000    1328  105
20        Ford      Mondeo    1600    1584   94
21        Opel    Insignia    2000    1428   99
22    Mercedes     C-Class    2100    1365   99
23       Skoda     Octavia    1600    1415   99
24       Volvo         S60    2000    1415   99
25    Mercedes         CLA    1500    1465  102
26        Audi          A4    2000    1490  104
27        Audi          A6    2000    1725  114
28       Volvo         V70    1600    1523  109
29         BMW           5    2000    1705  114
30    Mercedes     E-Class    2100    1605  115
31       Volvo        XC70    2000    1746  117
32        Ford       B-Max    1600    1235  104
33         BMW         216    1600    1390  108
34        Opel      Zafira    1600    1405  109
35    Mercedes         SLK    2500    1395  120

In [51]:
df.head()
#or
df.head(10)

Car       Model  Volume  Weight  CO2
0      Toyoty        Aygo    1000     790   99
1  Mitsubishi  Space Star    1200    1160   95
2       Skoda      Citigo    1000     929   95
3        Fiat         500     900     865   90
4        Mini      Cooper    1500    1140  105
5          VW         Up!    1000     929  105
6       Skoda       Fabia    1400    1109   90
7    Mercedes     A-Class    1500    1365   92
8        Ford      Fiesta    1500    1112   98
9        Audi          A1    1600    1150   99

In [52]:
df.tail()
#or
df.tail(10)

Car    Model  Volume  Weight  CO2
26      Audi       A4    2000    1490  104
27      Audi       A6    2000    1725  114
28     Volvo      V70    1600    1523  109
29       BMW        5    2000    1705  114
30  Mercedes  E-Class    2100    1605  115
31     Volvo     XC70    2000    1746  117
32      Ford    B-Max    1600    1235  104
33       BMW      216    1600    1390  108
34      Opel   Zafira    1600    1405  109
35  Mercedes      SLK    2500    1395  120

In [53]:
new_df = df.dropna()
new_df

Car       Model  Volume  Weight  CO2
0       Toyoty        Aygo    1000     790   99
1   Mitsubishi  Space Star    1200    1160   95
2        Skoda      Citigo    1000     929   95
3         Fiat         500     900     865   90
4         Mini      Cooper    1500    1140  105
5           VW         Up!    1000     929  105
6        Skoda       Fabia    1400    1109   90
7     Mercedes     A-Class    1500    1365   92
8         Ford      Fiesta    1500    1112   98
9         Audi          A1    1600    1150   99
10     Hyundai         I20    1100     980   99
11      Suzuki       Swift    1300     990  101
12        Ford      Fiesta    1000    1112   99
13       Honda       Civic    1600    1252   94
14      Hundai         I30    1600    1326   97
15        Opel       Astra    1600    1330   97
16         BMW           1    1600    1365   99
17       Mazda           3    2200    1280  104
18       Skoda       Rapid    1600    1119  104
19        Ford       Focus    2000    1328  105
20        Ford      Mondeo    1600    1584   94
21        Opel    Insignia    2000    1428   99
22    Mercedes     C-Class    2100    1365   99
23       Skoda     Octavia    1600    1415   99
24       Volvo         S60    2000    1415   99
25    Mercedes         CLA    1500    1465  102
26        Audi          A4    2000    1490  104
27        Audi          A6    2000    1725  114
28       Volvo         V70    1600    1523  109
29         BMW           5    2000    1705  114
30    Mercedes     E-Class    2100    1605  115
31       Volvo        XC70    2000    1746  117
32        Ford       B-Max    1600    1235  104
33         BMW         216    1600    1390  108
34        Opel      Zafira    1600    1405  109
35    Mercedes         SLK    2500    1395  120

In [54]:
df.fillna(130, inplace=True)

In [55]:
df.loc[7,'weight'] = 2500

In [56]:
for x in df.index :
    if df.loc[x , "weight"] > 1000:
        df.loc[x , 'weight'] = 1000
df

Car       Model  Volume  Weight  CO2  weight
0       Toyoty        Aygo    1000     790   99     NaN
1   Mitsubishi  Space Star    1200    1160   95     NaN
2        Skoda      Citigo    1000     929   95     NaN
3         Fiat         500     900     865   90     NaN
4         Mini      Cooper    1500    1140  105     NaN
5           VW         Up!    1000     929  105     NaN
6        Skoda       Fabia    1400    1109   90     NaN
7     Mercedes     A-Class    1500    1365   92  1000.0
8         Ford      Fiesta    1500    1112   98     NaN
9         Audi          A1    1600    1150   99     NaN
10     Hyundai         I20    1100     980   99     NaN
11      Suzuki       Swift    1300     990  101     NaN
12        Ford      Fiesta    1000    1112   99     NaN
13       Honda       Civic    1600    1252   94     NaN
14      Hundai         I30    1600    1326   97     NaN
15        Opel       Astra    1600    1330   97     NaN
16         BMW           1    1600    1365   99     NaN
17       Mazda           3    2200    1280  104     NaN
18       Skoda       Rapid    1600    1119  104     NaN
19        Ford       Focus    2000    1328  105     NaN
20        Ford      Mondeo    1600    1584   94     NaN
21        Opel    Insignia    2000    1428   99     NaN
22    Mercedes     C-Class    2100    1365   99     NaN
23       Skoda     Octavia    1600    1415   99     NaN
24       Volvo         S60    2000    1415   99     NaN
25    Mercedes         CLA    1500    1465  102     NaN
26        Audi          A4    2000    1490  104     NaN
27        Audi          A6    2000    1725  114     NaN
28       Volvo         V70    1600    1523  109     NaN
29         BMW           5    2000    1705  114     NaN
30    Mercedes     E-Class    2100    1605  115     NaN
31       Volvo        XC70    2000    1746  117     NaN
32        Ford       B-Max    1600    1235  104     NaN
33         BMW         216    1600    1390  108     NaN
34        Opel      Zafira    1600    1405  109     NaN
35    Mercedes         SLK    2500    1395  120     NaN

In [57]:
for x in df.index :
    if df.loc[x , 'weight'] > 1000:
        df.drop(x , inplace = True)
df

Car       Model  Volume  Weight  CO2  weight
0       Toyoty        Aygo    1000     790   99     NaN
1   Mitsubishi  Space Star    1200    1160   95     NaN
2        Skoda      Citigo    1000     929   95     NaN
3         Fiat         500     900     865   90     NaN
4         Mini      Cooper    1500    1140  105     NaN
5           VW         Up!    1000     929  105     NaN
6        Skoda       Fabia    1400    1109   90     NaN
7     Mercedes     A-Class    1500    1365   92  1000.0
8         Ford      Fiesta    1500    1112   98     NaN
9         Audi          A1    1600    1150   99     NaN
10     Hyundai         I20    1100     980   99     NaN
11      Suzuki       Swift    1300     990  101     NaN
12        Ford      Fiesta    1000    1112   99     NaN
13       Honda       Civic    1600    1252   94     NaN
14      Hundai         I30    1600    1326   97     NaN
15        Opel       Astra    1600    1330   97     NaN
16         BMW           1    1600    1365   99     NaN
17       Mazda           3    2200    1280  104     NaN
18       Skoda       Rapid    1600    1119  104     NaN
19        Ford       Focus    2000    1328  105     NaN
20        Ford      Mondeo    1600    1584   94     NaN
21        Opel    Insignia    2000    1428   99     NaN
22    Mercedes     C-Class    2100    1365   99     NaN
23       Skoda     Octavia    1600    1415   99     NaN
24       Volvo         S60    2000    1415   99     NaN
25    Mercedes         CLA    1500    1465  102     NaN
26        Audi          A4    2000    1490  104     NaN
27        Audi          A6    2000    1725  114     NaN
28       Volvo         V70    1600    1523  109     NaN
29         BMW           5    2000    1705  114     NaN
30    Mercedes     E-Class    2100    1605  115     NaN
31       Volvo        XC70    2000    1746  117     NaN
32        Ford       B-Max    1600    1235  104     NaN
33         BMW         216    1600    1390  108     NaN
34        Opel      Zafira    1600    1405  109     NaN
35    Mercedes         SLK    2500    1395  120     NaN

In [58]:
df.drop_duplicates(inplace = True)
df

Car       Model  Volume  Weight  CO2  weight
0       Toyoty        Aygo    1000     790   99     NaN
1   Mitsubishi  Space Star    1200    1160   95     NaN
2        Skoda      Citigo    1000     929   95     NaN
3         Fiat         500     900     865   90     NaN
4         Mini      Cooper    1500    1140  105     NaN
5           VW         Up!    1000     929  105     NaN
6        Skoda       Fabia    1400    1109   90     NaN
7     Mercedes     A-Class    1500    1365   92  1000.0
8         Ford      Fiesta    1500    1112   98     NaN
9         Audi          A1    1600    1150   99     NaN
10     Hyundai         I20    1100     980   99     NaN
11      Suzuki       Swift    1300     990  101     NaN
12        Ford      Fiesta    1000    1112   99     NaN
13       Honda       Civic    1600    1252   94     NaN
14      Hundai         I30    1600    1326   97     NaN
15        Opel       Astra    1600    1330   97     NaN
16         BMW           1    1600    1365   99     NaN
17       Mazda           3    2200    1280  104     NaN
18       Skoda       Rapid    1600    1119  104     NaN
19        Ford       Focus    2000    1328  105     NaN
20        Ford      Mondeo    1600    1584   94     NaN
21        Opel    Insignia    2000    1428   99     NaN
22    Mercedes     C-Class    2100    1365   99     NaN
23       Skoda     Octavia    1600    1415   99     NaN
24       Volvo         S60    2000    1415   99     NaN
25    Mercedes         CLA    1500    1465  102     NaN
26        Audi          A4    2000    1490  104     NaN
27        Audi          A6    2000    1725  114     NaN
28       Volvo         V70    1600    1523  109     NaN
29         BMW           5    2000    1705  114     NaN
30    Mercedes     E-Class    2100    1605  115     NaN
31       Volvo        XC70    2000    1746  117     NaN
32        Ford       B-Max    1600    1235  104     NaN
33         BMW         216    1600    1390  108     NaN
34        Opel      Zafira    1600    1405  109     NaN
35    Mercedes         SLK    2500    1395  120     NaN

In [59]:
df.corr()

ValueError: could not convert string to float: 'Toyoty'